
services:
  db:
    image: mysql:5.7
    container_name: dicom-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dicom_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: dicom-backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: dicom_db
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "4000:4000"

  frontend:
    build: ./dicom-frontend
    container_name: dicom-frontend
    restart: always
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:4000
    ports:
      - "5173:5173"

  flask:
    build: ./python-pydicom-ms
    container_name: dicom-flask
    restart: always
    depends_on:
      - db
    environment:
      FLASK_ENV: production
    volumes:
      - ./python-pydicom-ms/uploads:/app/uploads
    ports:
      - "5001:5001"

volumes:
  db_data:
    driver: local
